---
# - name: Remove old repos
#   shell: rm /etc/yum.repos.d/*.repo
#
# - name: Yum repository configuration for instances
#   copy:
#      src: files/internal.repo
#      dest: /etc/yum.repos.d/internal.repo
#      mode: 0644
#      backup: yes

# - name: Ensure Python 3.6.5 is installed
#   win_chocolatey:
#     name: python
#     version: '3.6.5'
#     install_args:
#       - TargetDir: 'c:\Python36'
#       - InstallAllUsers: '1'
#     state: present
#   with_items:

- name: Ensure Environment Variables are set correctly
  win_path:
    elements:
      - 'c:\python36'
      - 'c:\python36\Scripts'

- name: Ensure Python Modules required are present
  pip:
    name: "{{ item }}"
  with_items:
    - flask
    - flask_upload
    - flask_wtf
    - wtforms
    - keras
    - tensorflow
    - numpy
    - imutils
    - opencv-python

# - name: Ensure Python Modules are present
#   win_shell: pip flask wfastcgi
#   create_file: 'c:\python36\requirements_ok.txt'



# - name: Ensure Pre Reqs Packages are present
#   yum:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - python-pip
#     - libSM
#     - libXext
#     - libXrender
