---
- name: Ensure Packages required are installed
  win_chocolatey:
    name: "{{ item.key }}"
    version: "{{ item.value.version }}"
    install_args:
      - TargetDir: "{{ item.value.dir | default(omit) }}"
      - InstallAllUsers: "{{ item.value.allusers | default(omit) }}"
    state: present
  loop: "{{ lookup('dict',packages)}}"

- name: Ensure Environment Variables are set correctly
  win_path:
    elements:
      - 'c:\python36'
      - 'c:\python36\Scripts'
      - 'c:\Program Files\git'

- name: Ensure Logs Directory is present
  win_file:
    path: c:\Logs
    state: directory

- name: Ensure Python Modules are present
  win_shell: pip install flask wfastcgi flask_wtf flask_uploads wtforms keras tensorflow numpy imutils opencv-python >> c:\logs\requirements_ok.log
  args:
    creates: 'c:\logs\requirements_ok.log'
