---

- name: Ensure Packages required are installed
  win_chocolatey:
    name: "{{ item.key }}"
    version: "{{ item.value.version }}"
    install_args:
      - TargetDir: "{{ item.value.dir}}"
      - InstallAllUsers: "{{ item.value.allusers }}"
    state: present
  loop: "{{ lookup('dict',packages)}}"

- name: Ensure Environment Variables are set correctly
  win_path:
    elements:
      - 'c:\python36'
      - 'c:\python36\Scripts'
      - 'c:\Program Files\git'

- name: Ensure Python Modules are present
  win_shell: pip install flask wfastcgi flask_uploads wtforms keras tensorflow numpy imutils opencv-python
  args:
    creates: 'c:\requirements_ok.txt'
