---
- hosts: localhost
  gather_facts: false
  # roles:
  #   - osp_facts

# - hosts: frontends
#   become: yes
#   roles:
#     - config.role
#     - haproxy.role

- hosts: application_web
  become: yes
  roles:
    - config.role
    - tomcat.role

- hosts: application_db
  become: yes
  roles:
    - config.role
    - postgresql.role
