---
- name: Deploy Hot Dog Not Hot Dog App
  hosts: windows
  become: yes

  tasks:

    - name: Ensure Pre Reqs Packages are present
      include_role:
        name: config.role
        tasks_from: config_win.yml

    # - name: Ensure App is present
    #   include_role:
    #     name: hdnhd.role
    #     tasks_from: install_app.yml
