---
- name: Ensure Default Web Site is not present
  win_iis_website:
    name: 'Default Web Site'
    state: absent

- name: Ensure App Web Site directory is present
  win_file:
    path: 'c:\app\app'
    state: directory

- name: Ensure App web site is present
  win_iis_website:
    name: app
    binding: 80
    physical_path: 'c:\app\app\'
    state: present

- name: Ensure App Web Site is well configured
  win_dsc:
    resource_name: xIISModule
    ensure: present
    name: 'app'
    path: 'c:\python36\python.exe|c:\python36\lib\site-packages\wfastcgi.py'
    requestpath: '*'
    SiteName: app
    ModuleType: fastcgimodule
