---
- name: Ensure Windows Powershell DSC Feature is present
  win_feature:
    name: dsc-service
    state: present

- name: Download xWebAdministration DSC module
  win_get_url:
    url: 'https://gallery.technet.microsoft.com/xWebAdministration-Module-3c8bb6be/file/135740/1/xWebAdministration_1.3.2.4.zip'
    dest: 'c:\'

- name: Unzip xWebAdministration DSC module
  win_unzip:
    src: 'c:\xWebAdministration_1.3.2.4.zip'
    dest: 'c:\Program Files\WindowsPowerShell\Modules\xWebAdministration'
    # creates: 'c:\Program Files\WindowsPowerShell\Modules\xWebAdministration_1.3.2.4'
    delete_archive: yes

- name: Ensure App Web Site directory is present
  win_file:
    path: 'c:\app\app'
    state: directory

# - name: Ensure Default Web Site is absent
#   win_dsc:
#     resource_name: xWebSite
#     ensure: present
#     name: 'Default Web Site'
#     state: stopped
#     physicalpath: 'c:\inetpub\wwwroot\'

- name: Ensure App ApplicationPool is present
  win_dsc:
    resource_name: xWebAppPool
    ensure: present
    name: app
    state: started

- name: Ensure App Web Site is present
  win_dsc:
    resource_name: xWebSite
    ensure: present
    name: app
    state: started
    physicalpath: c:\app\app\
    BindingInfo:
      - protocol: http
        port: 80
        ipaddress: '*'
    applicationpool: app

- name: Ensure App Web Site Module is well configured
  win_dsc:
    resource_name: xIISModule
    ensure: present
    name: 'app'
    path: 'c:\python36\python.exe|c:\python36\lib\site-packages\wfastcgi.py'
    requestpath: '*'
    verb: '*'
    SiteName: app
    ModuleType: FastCgiModule

- name: Ensure Key/Value are well configured for App
  win_dsc:
    resource_name: xWebConfigKeyValue
    ensure: present
    Configsection: appsettings
    key: 'PYTHONPATH'
    value: 'c:\python36\lib\site-packages\'
    key: 'WSGI_HANDLER'
    value: 'app.app'
    websitepath: 'iis:sites\app'
