---

- name: Ensure IIS and sub features are present
  win_feature:
    name: web-server
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Ensure wFastCGI is enabled
  win_shell: wfastcgi-enable >> c:\logs\wfastcgi_ok.log
  args:
    creates: 'c:\logs\wfastcgi_ok.log'
  become: yes
