---
- name: Ensure IIS and sub features are present
  win_features:
    name: "web-server, web-cgi, web-default-doc, web-dir-browsing, web-http-errors, web-static-content, web-http-logging, web-stat-compression, web-filtering"
    state: present
    include_sub_features: no
    include_management_tools: yes
