---
- name: create temporary directory to get app
  tempfile:
    state: directory
    suffix: app
  register: r_tempfile
  connection: local
  run_once: yes
  become: no

- name: git clone the app
  git:
    repo: "{{ app }}"
    version: "{{ ver }}"
    dest: "{{ r_tempfile.path }}"
  connection: local
  run_once: yes
  become: no

- name: copy app to nodes
  win_copy:
    src: "{{ r_tempfile.path }}/"
    dest: "c:\\app\\"
  become: yes
  notify: restart iis
