---
- name: create temporary directory to get app
  tempfile:
    state: directory
    suffix: app
  register: r_tempfile
  delegate_to: localhost
  run_once: yes
  become: no

- name: git clone the app specific version
  git:
    repo: "{{ app }}"
    version: "{{ version }}"
    dest: "{{ r_tempfile.path }}"
  delegate_to: localhost
  run_once: yes
  become: no
  when:
    - version is defined and version != ""

- name: git clone the app latest comit
  git:
    repo: "{{ app }}"
    dest: "{{ r_tempfile.path }}"
  delegate_to: localhost
  run_once: yes
  become: no
  when:
    - version is not defined or version == ""

- name: Remove git history
  file:
    path: "{{ r_tempfile.path }}/.git"
    state: absent
  delegate_to: localhost
  run_once: yes
  become: no

- name: Import Model from S3
  get_url:
    url: "{{ bucket }}/model-{{ version }}.model"
    dest: "{{ r_tempfile.path }}/app/model/model.model"
    force: yes
  delegate_to: localhost
  run_once: yes
  become: no

- name: Set an environment variable for Web App
  win_environment:
    state: present
    name: OBJECT_STORE
    value: "{{ object_store }}"
    level: machine

- name: copy app to nodes
  win_copy:
    src: "{{ r_tempfile.path }}/"
    dest: c:\app\
  notify: "restart iis web servers"

- name: Ensure permissions on directory are present
  win_acl:
    user: IUSR
    path: c\app\
    type: allow
    rights: FullControl
  notify: "restart iis web servers"
