---
- name: create temporary directory to get app
  tempfile:
    state: directory
    suffix: app
  register: r_tempfile
  delegate_to: localhost
  run_once: yes
  become: no

- name: Git clone the app
  git:
    repo: "{{ app }}"
    version: "{{ ver }}"
    dest: "{{ r_tempfile.path }}"
  run_once: yes
  delegate_to: localhost
  notify: restart iis

- name: copy app to nodes
  win_copy:
    src: "{{ r_tempfile.path }}/"
    dest: c:\app\
  notify: "restart iis web servers"
